apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://rubxkube.github.io/common-charts/
      chart: common
      targetRevision: v0.5.0
      helm:
        values: |
          name: "byparr"
          image:
            repository: ghcr.io/thephaseless/byparr
            tag: "v2.1.0"
          deployment:
            port: 8191
          service:
            containerPort: 8191
    - repoURL: https://rubxkube.github.io/charts/
      chart: jackett
      targetRevision: 1.3.2
      helm:
        values: |
          common:
            ingress:
              enabled: true
              hostName: "indexer.<path:kv/cluster#domain>"
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: cloudflare
              tls:
                enabled: true
                secretName: "jackett-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
