# Shared Restic credentials pulled from Vault.
# Vault path: kv/restic
# Required keys:
#   - AWS_ACCESS_KEY_ID     (Minio access key)
#   - AWS_SECRET_ACCESS_KEY (Minio secret key)
#   - RESTIC_PASSWORD       (Restic encryption password)
#
# Per-app repositories are stored as RESTIC_REPOSITORY_<APP> in Vault.
# Each app's ExternalSecret should reference the specific repository key.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-base-credentials
  namespace: volsync-system
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: restic-base-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: restic
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: restic
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: restic
        property: RESTIC_PASSWORD
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: restic
        property: RESTIC_REPOSITORY
